# Menus
menu:
  首页: /
  归档: archives
  分类: categories
  标签: tags
  关于: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Pylixm
        author_title: Web Developer & Pythoner 
        location: BeiJing, China
        follow: https://github.com/pylixm/
    highlight: github #solarized-light
    sidebar: right # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/ppoffice/hexo-theme-icarus
        知乎: https://www.zhihu.com/people/iamxcc
        # V2EX: https://www.v2ex.com/member/ybzbxcc
        # 简书: http://www.jianshu.com/users/a820fe80f428/timeline
        rss: /atom.xml
    social_icons:
        github: github
        知乎: bookmark
        # V2EX: codepen
        # 简书: book
        rss: rss


    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - tagcloud
    # - series
    # - recent_posts
    #- category
    - archive
    #- tag
    - links

# Series
series:
    Sublime:
        image_url: http://7xveyh.com1.z0.glb.clouddn.com/sublime-text-mastery.jpg
        title: 优雅的Sublime
    LeetCode: 
        image_url: http://7xveyh.com1.z0.glb.clouddn.com/2013111315172517727.jpg
        title: LeetCode题解
    算法: 
        image_url: http://7xveyh.com1.z0.glb.clouddn.com/2016080413315664241_640x360.jpeg
        title: 有趣的算法

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: pylixm # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: #UA-82072441-1 # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: true # enter Baidu Analytics hash key

# Script Vendors.
# Set a CDN address for the vendor you want to customize.
vendors:
    jquery: //cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js
    fontawesome: //maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        程序员集散地: http://www.iwebtools.cn


# ---------------------------------------------------------------
# Third Party Services Settings 
# ---------------------------------------------------------------

# MathJax Support
mathjax:
  enable: true
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: OBJcj4PU8JI0zDfu0HJSrG6W-gzGzoHsz #<app_id>
  app_key: tBtFzC72xIlgo2UFbA33nqmU #<app_key>


language: zh-CN

auto_excerpt:
  enable: false 
  length: 300 